version: '3.8'

services:
  app:
    build: .
    container_name: hybrid-app
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      DB_URL: postgresql://hybridapp_s1g9_user:hfI3n2adtsr5tMZY3f5aNOO4BHmczj8M@dpg-d3nuoqhr0fns73dvp760-a.oregon-postgres.render.com/hybridapp_s1g9?sslmode=require
